#### WARNING
#### Change token permissions to make it run
#### on the repo : settings => actions => general => R/W permission in workflow category
name: Issue assigned
on:
  issues:
    types:
      - assigned

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create Issue Branch
        run: |
          git checkout -b support/${{ github.event.issue.id }}-${{ github.event.issue.title }}
          git push origin support/${{ github.event.issue.id }}-${{ github.event.issue.title }}